config/routes.rb
Rails.application.routes.draw do
  root to: 'public/books#index'
  namespace :admin do
    get 'dashboard/index'
    resources :books
    resources :scenarios
    resources :profiles
  end
  scope module: :public do
    get 'dashboard/index'
    resources :books, only: [:index, :show]
    resources :scenarios, only: [:index, :show]
    resources :profiles, only: [:index, :show]
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'login', to: 'users/sessions#new'
    delete 'logout', to: 'users/sessions#destroy'
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminApplicationController
  def index
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/admin/dashboard/index.html.slim
.row
  .col
  .col6 
    - if current_user.profile.present?
      h1
        |"ようこそ　#{current_user.profile.name}　さん"
    - else
      h1
        |"ようこそ　#{current_user.id}　さん"
  .col

.mt-5
  table.table.table-hover
    thead.thead-default
      tbody
        - if current_user.profile.present?
          tr
            td = 'プロフィール閲覧'
            td = link_to 'プロフィール閲覧', admin_profile_path(current_user.profile), class: 'btn btn-primary'
          tr
            td = 'プロフィール編集'
            td = link_to 'プロフィール編集', edit_admin_profile_path(current_user.profile), class: 'btn btn-primary'          
        - else
          tr
            td = 'プロフィールの作成'
            td = link_to 'プロフィール', new_admin_profile_path, class: 'btn btn-primary'
        tr
          td = 'ゲームブックを作る'
          td = link_to 'ブック作成', new_admin_book_path, class: 'btn btn-primary'
        tr
          td = '作ったブックの一覧'
          td = link_to 'ブック一覧', admin_books_path, class: 'btn btn-primary'
        - if current_user.books.present?
          tr
            td = 'シナリオを作成'
            td = link_to 'シナリオ作成', new_admin_scenario_path, class: 'btn btn-primary'
          tr
            td = 'シナリオの一覧'
            td = link_to 'シナリオ一覧', admin_scenarios_path, class: 'btn btn-primary'