config/routes.rb
Rails.application.routes.draw do
  root to: 'public/books#index'
  namespace :admin do
    get 'dashboard/index'
    resources :books
    resources :scenarios
    resources :profiles
  end
  scope module: :public do
    get 'dashboard/index'
    resources :books, only: [:index, :show]
    resources :scenarios, only: [:index, :show]
    resources :profiles, only: [:index, :show]
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'login', to: 'users/sessions#new'
    delete 'logout', to: 'users/sessions#destroy'
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/controllers/admin/profiles_controller.rb
class Admin::ProfilesController < AdminApplicationController
  before_action :set_profile, only: [:index, :show, :edit, :update, :destroy]

  # GET /profiles
  def index
  end

  # GET /profiles/1
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  def create
    @profile = Profile.new(profile_params)

    if @profile.save
      redirect_to @profile, notice: 'Profile was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /profiles/1
  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /profiles/1
  def destroy
    @profile.destroy
    redirect_to profile_url, notice: 'Profile was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = current_user.profile
    end

    # Only allow a trusted parameter "white list" through.
    def profile_params
      params.require(:profile).permit(:name, :comment, :user_id)
    end
end

app/helpers/admin/profiles_helper.rb
module Admin::ProfilesHelper
end

app/views/admin/profiles/_form.html.slim
= form_with model: [ :admin, @profile ], local: true do |f|
  .form-group.row
    .col-sm-3
      = f.label :name, 'ユーザー名', class: 'col-form-label'
    .col-sm-9
      = f.text_field :name, class: 'form-control'
  .form-group.row
    .col-sm-3
      = f.label :comment, 'コメント', class: 'col-form-label'
    .col-sm-9
      = f.text_area :comment, class: 'form-control'
  .form-group
      = f.submit '決定', class: 'btn btn-primary'

app/views/admin/profiles/edit.html.slim
.row
  .col
  .col6 
    h1 プロフィール編集
  .col

== render 'form', profile: @profile

= link_to '詳細', admin_profile_path(current_user.id), class: 'btn btn-primary'

app/views/admin/profiles/index.html.slim
.row
  .col
  .col6 
    h1 プロフィール
  .col

.mt-5
    table.table.table-hover
      thead.thead-default
    　　tr
      　　th ユーザー名
      　　th コメント
      　　th ユーザーid
      　　th
      　　th
      　　th

  　　tbody
      　tr
        　td = profile.name
        　td = profile.comment
        　td = profile.user
        　td = link_to '閲覧', admin_profiles_path(current_user.id), class: 'btn btn-outline-primary mr-3'
        　td = link_to '編集', edit_admin_profile_path(current_user.id), class: 'btn btn-primary mr-3'
        　td = link_to '削除', admin_profile_path, data: { confirm: '本当に削除しますか？' }, method: :delete, class: 'btn btn-danger'

app/views/admin/profiles/new.html.slim
.row
  .col
  .col6 
    h1 プロフィール作成
  .col

== render 'form', profile: @profile

= link_to '詳細', admin_profiles_path(current_user.id), class: 'btn btn-primary'

app/views/admin/profiles/show.html.slim
.row
  .col
  .col6 
    h1 プロフィール
  .col

.mt-5
  p#notice = notice

  p
    strong Name:
    = @profile.name
  p
    strong Comment:
    = @profile.comment
  p
    strong User:
    = @profile.user