config/routes.rb
Rails.application.routes.draw do
  root to: 'public/books#index'
  namespace :admin do
    get 'dashboard/index'
    resources :books
    resources :scenarios
    resources :profiles
  end
  scope module: :public do
    get 'dashboard/index'
    resources :books, only: [:index, :show]
    resources :scenarios, only: [:index, :show]
    resources :profiles, only: [:index, :show]
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'login', to: 'users/sessions#new'
    delete 'logout', to: 'users/sessions#destroy'
  end
end

app/models/scenario.rb
class Scenario < ApplicationRecord
  belongs_to :book

  validates :scenario_no, inclusion: { in: 1..999 }
  validates :next_no1, inclusion: { in: 0..999 }
  validates :next_no2, inclusion: { in: 0..999 }
  validates :next_no3, inclusion: { in: 0..999 }
end

app/controllers/admin/scenarios_controller.rb
class Admin::ScenariosController < AdminApplicationController
  before_action :set_scenario, only: [:show, :edit, :update, :destroy]

  # GET /scenarios
  def index
    @scenarios = Scenario.where(book_id: current_user.books.ids)
  end

  # GET /scenarios/1
  def show
    @next1 = Scenario.find_by(book_id: @scenario.book_id, scenario_no: @scenario.next_no1)
    @next2 = Scenario.find_by(book_id: @scenario.book_id, scenario_no: @scenario.next_no2)
    @next3 = Scenario.find_by(book_id: @scenario.book_id, scenario_no: @scenario.next_no3)    
  end

  # GET /scenarios/new
  def new
    @scenario = Scenario.new
  end

  # GET /scenarios/1/edit
  def edit
  end

  # POST /scenarios
  def create
    @scenario = Scenario.new(scenario_params)

    if @scenario.save
      redirect_to admin_scenarios_path, notice: 'Scenario was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /scenarios/1
  def update
    if @scenario.update(scenario_params)
      redirect_to admin_scenarios_path, notice: 'Scenario was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /scenarios/1
  def destroy
    @scenario.destroy
    redirect_to scenarios_url, notice: 'Scenario was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scenario
      @scenario = Scenario.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def scenario_params
      params.require(:scenario).permit(:scenario_no, :description, :next_no1, :next_no2, :next_no3, :book_id)
    end
end

app/helpers/admin/scenarios_helper.rb
module Admin::ScenariosHelper
end

app/views/admin/scenarios/_form.html.slim
.mt-5
  = form_with model: [ :admin, @scenario ], local: true do |f|
    .form-group.row
      .col-sm-3
        = f.label :book_id, 'ブック名', class: 'col-form-label'
      .col-sm-9
        = f.select :book_id, current_user.books.all.map{|b| [b.book_title, b.id]}
    .form-group.row
      .col-sm-3
        = f.label :scenario_no, 'シナリオ番号', class: 'col-form-label'
      .col-sm-9
        = f.number_field :scenario_no, min: 1, max: 999, class: 'form-control'
    .form-group.row
      .col-sm-3
        = f.label :description, 'シナリオ', class: 'col-form-label'
      .col-sm-9
        = f.text_area :description, class: 'form-control'
    .form-group.row
      .col-sm-3
        = f.label :next_no1, '選択肢１', class: 'col-form-label'
      .col-sm-9
        = f.number_field :next_no1, min: 0, max: 999, class: 'form-control'
    .form-group.row
      .col-sm-3
        = f.label :next_no2, '選択肢２', class: 'col-form-label'
      .col-sm-9
        = f.number_field :next_no2, min: 0, max: 999, class: 'form-control'
    .form-group.row
      .col-sm-3
        = f.label :next_no3, '選択肢３', class: 'col-form-label'
      .col-sm-9
        = f.number_field :next_no3, min: 0, max: 999, class: 'form-control'
    .form-group
      = f.submit '決定', class: 'btn btn-primary'

app/views/admin/scenarios/edit.html.slim
h1 シナリオ編集

.nav.justify-content-end
  = link_to 'トップに戻る', '/', class: 'btn btn-primary mb-5'

== render 'form', scenario: @scenario

= link_to '一覧へ戻る', admin_scenarios_path, class: 'btn btn-primary mr-3'

app/views/admin/scenarios/index.html.slim
.row
  .col
  .col6 
    h1 シナリオ番号一覧
  .col

.nav.justify-content-end
  = link_to 'トップに戻る', admin_books_path, class: 'btn btn-primary mb-5'

table.table.table-hover.table-striped
  thead
    tr
      th タイトル
      th シナリオ番号
      th 内容
      th 選択肢１
      th 選択肢２
      th 選択肢３
      th
      th
      th

  tbody
    - @scenarios.each do |scenario|
      tr
        td = scenario.book.book_title
        td = scenario.scenario_no
        td = truncate(scenario.description, length: 5)
        td = scenario.next_no1
        td = scenario.next_no2
        td = scenario.next_no3
        td = link_to '読む', admin_scenario_url(scenario), class: 'btn btn-outline-primary'
        td = link_to '編集', edit_admin_scenario_path(scenario), class: 'btn btn-primary'
        td = link_to '削除', admin_scenario_url(scenario), data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-outline-danger'

br

= link_to '新規作成', new_admin_scenario_path, class: 'btn btn-primary'

app/views/admin/scenarios/new.html.slim
.row
  .col
  .col6 
    h1 シナリオ作成 
  .col

== render 'form', scenario: @scenario

= link_to '一覧へ戻る', admin_scenarios_path, class: 'btn btn-primary'

app/views/admin/scenarios/show.html.slim
h1 
  = @scenario.scenario_no
= @scenario.description
.row
  .col2
    -if @next1.present?
      = link_to "#{@scenario.next_no1}へ行く", admin_scenario_url(@next1), class: 'btn btn-outline-primary' unless @scenario.next_no1 == 0
  .col2
    - if @next2.present?
      = link_to "#{@scenario.next_no2}へ行く", admin_scenario_url(@next2), class: 'btn btn-outline-primary' unless @scenario.next_no2 == 0
  .col2
    - if @next3.present?
      = link_to "#{@scenario.next_no3}へ行く", admin_scenario_url(@next3), class: 'btn btn-outline-primary' unless @scenario.next_no3 == 0